import { InventoryType } from "./Type";

export enum ParentType {
  None,
  Booster,
  Captura_Scene,
  Color_Palette,
  Consumable,
  Cosmetic,
  Decoration,
  Emote,
  Glyph,
  Mod,
  Pack,
  Quest,
  Sentinel,
  Somachord,
  Void_Relic,
  Weapon,
}

export const ParentTypeMap: Record<ParentType, InventoryType[]> = {
  [ParentType.None]: [InventoryType.None],
  [ParentType.Booster]: [InventoryType.Booster],
  [ParentType.Captura_Scene]: [InventoryType.Captura_Scene],
  [ParentType.Color_Palette]: [InventoryType.Color_Palette],
  [ParentType.Consumable]: [InventoryType.Consumable],
  [ParentType.Cosmetic]: [
    InventoryType.Cosmetic_Archwing,
    InventoryType.Cosmetic_Armor,
    InventoryType.Cosmetic_Emblem,
    InventoryType.Cosmetic_Ephemera,
    InventoryType.Cosmetic_KDrive,
    InventoryType.Cosmetic_Kavat,
    InventoryType.Cosmetic_Kubrow,
    InventoryType.Cosmetic_Landing_Craft,
    InventoryType.Cosmetic_MOA,
    InventoryType.Cosmetic_Operator,
    InventoryType.Cosmetic_Orbiter,
    InventoryType.Cosmetic_Sentinel,
    InventoryType.Cosmetic_Sigil,
    InventoryType.Cosmetic_Syandana,
    InventoryType.Cosmetic_Warframe_Skin,
    InventoryType.Cosmetic_Weapon,
  ],
  [ParentType.Decoration]: [InventoryType.Decoration],
  [ParentType.Emote]: [InventoryType.Emote],
  [ParentType.Glyph]: [InventoryType.Glyph],
  [ParentType.Mod]: [
    InventoryType.Regular,
    InventoryType.Mod_Prime,
    InventoryType.Mod_Stance,
  ],
  [ParentType.Pack]: [InventoryType.Pack],
  [ParentType.Quest]: [InventoryType.Quest],
  [ParentType.Sentinel]: [InventoryType.Sentinel],
  [ParentType.Somachord]: [InventoryType.Somachord],
  [ParentType.Void_Relic]: [InventoryType.Void_Relic],
  [ParentType.Weapon]: [InventoryType.Weapon, InventoryType.Weapon_Archwing],
};
