export enum InventoryType {
  None,
  Booster,
  Captura_Scene,
  Color_Palette,
  Consumable,
  Cosmetic_Archwing,
  Cosmetic_Armor,
  Cosmetic_Emblem,
  Cosmetic_Ephemera,
  Cosmetic_KDrive,
  Cosmetic_Kavat,
  Cosmetic_Kubrow,
  Cosmetic_Landing_Craft,
  Cosmetic_MOA,
  Cosmetic_Operator,
  Cosmetic_Orbiter,
  Cosmetic_Sentinel,
  Cosmetic_Sigil,
  Cosmetic_Syandana,
  Cosmetic_Warframe_Skin,
  Cosmetic_Weapon,
  Decoration,
  Emote,
  Glyph,
  Regular,
  Mod_Prime,
  Mod_Stance,
  Pack,
  Quest,
  Sentinel,
  Somachord,
  Void_Relic,
  Weapon,
  Weapon_Archwing,
}

export const InventoryTypeNames: Record<InventoryType, string> = {
  [InventoryType.None]: "None",
  [InventoryType.Booster]: "Booster",
  [InventoryType.Captura_Scene]: "Captura Scene",
  [InventoryType.Color_Palette]: "Color Palette",
  [InventoryType.Consumable]: "Consumable",
  [InventoryType.Cosmetic_Archwing]: "Archwing",
  [InventoryType.Cosmetic_Armor]: "Armor",
  [InventoryType.Cosmetic_Emblem]: "Emblem",
  [InventoryType.Cosmetic_Ephemera]: "Ephemera",
  [InventoryType.Cosmetic_KDrive]: "K-Drive",
  [InventoryType.Cosmetic_Kavat]: "Kavat",
  [InventoryType.Cosmetic_Kubrow]: "Kubrow",
  [InventoryType.Cosmetic_Landing_Craft]: "Landing Craft",
  [InventoryType.Cosmetic_MOA]: "MOA",
  [InventoryType.Cosmetic_Operator]: "Operator",
  [InventoryType.Cosmetic_Orbiter]: "Orbiter",
  [InventoryType.Cosmetic_Sentinel]: "Sentinel",
  [InventoryType.Cosmetic_Sigil]: "Sigil",
  [InventoryType.Cosmetic_Syandana]: "Syandana",
  [InventoryType.Cosmetic_Warframe_Skin]: "Warframe Skin",
  [InventoryType.Cosmetic_Weapon]: "Weapon",
  [InventoryType.Decoration]: "Decoration",
  [InventoryType.Emote]: "Emote",
  [InventoryType.Glyph]: "Glyph",
  [InventoryType.Regular]: "Regular",
  [InventoryType.Mod_Prime]: "Prime Mod",
  [InventoryType.Mod_Stance]: "Stance Mod",
  [InventoryType.Pack]: "Mod Pack",
  [InventoryType.Quest]: "Quest",
  [InventoryType.Sentinel]: "Sentinel",
  [InventoryType.Somachord]: "Somachord",
  [InventoryType.Void_Relic]: "Void Relic",
  [InventoryType.Weapon]: "Weapon",
  [InventoryType.Weapon_Archwing]: "Archwing Weapon",
}
